#!/usr/bin/env ansible-playbook
- gather_facts: true
  connection: local
  hosts: 
    localhost
  vars_prompt:
    - name: baseImageFilename
      default: "CentOS-7-x86_64-GenericCloud.qcow2"
      private: no
    - name: vmTitle
      default: "untitled"
      private: no
    - name: ramMb
      default: 8192
      private: no
    - name: count
      default: 1
      private: no
  roles: 
    - create-libvirt-vm
