# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"


  (1..20).each do |i|
    config.vm.define "app-#{i}" do |v|
      v.vm.provider "libvirt" do |pmv|
        pmv.memory = 2048
      end
    end
  end
end
