---
- yum_repository: name=jenkins baseurl=http://pkg.jenkins.io/redhat gpgcheck=no enabled=yes description=Jenkins
- yum: name={{item}} state=present
  with_items:
    - zip
    - httpd
    - jenkins
    - java
    - pytest
    - make
    - autoconf
    - php
    - php-phpunit-PHPUnit
    - ant
    - maven
    - java
    - puppet
    - rubygem-puppet-lint
    - npm
    - nodeunit
    - composer
    - cmake
    - mariadb-server
    - mariadb
    - rpm-build
- lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^JENKINS_ARGS='
    line: 'JENKINS_ARGS="--prefix=/jenkins" '
    state: present
- stat: 
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: initialAdminPasswordFile
- shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: adminPassword
  when: initialAdminPasswordFile.stat.exists
- name: adminPassword
  debug: msg={{adminPassword.stdout}}
  when: initialAdminPasswordFile.stat.exists
- name: copy proxy conf to httpd
  copy: 
    src: jenkins-proxy.conf
    dest: /etc/httpd/conf.d/jenkins-proxy.conf
- copy: 
    src: index.htm
    dest: /var/www/html/index.html
- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
- service: name={{item}} state=started
  with_items:
    - httpd
    - jenkins
    - mariadb

