#!/bin/sh

# Change your keymap:
xmodmap "/home/pi/.Xmodmap"

which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

/usr/bin/midori -e Fullscreen -a http://upsilon-web.teratan.net/?login=rpi1 -i 120 &
/usr/bin/unclutter -idle 1 &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
