- yum:
    name: "{{ package }}"
  vars:
    package:
      - mariadb-server
      - mariadb

- service:
    name: mariadb
    state: started
    enabled: true

- firewalld:
    service: mysql
    state: enabled
    permanent: true

- service: 
    name: firewalld
    state: restarted

