- debug:
    msg: "using directory: {{ baseImageDirectory }}"

- stat:
    path: "{{ baseImageDirectory }}/{{ baseImageFilename }}"

- when: vmCustomize == "cloud-init"
  block:
  - name: generate cloud-init
    template: 
      src=cloudinit.j2
      dest=/tmp/meta-data

  - name: generate user-data
    template:
      src: user-data.j2
      dest: /tmp/user-data

  - name: genisoimage
    command: genisoimage -output "/var/lib/libvirt/images/{{ item }}.iso" -volid cidata -joliet -r /tmp/meta-data /tmp/user-data

- name: copy disk
  copy: 
    src: "{{ baseImageDirectory }}/{{ baseImageFilename }}"
    dest: /var/lib/libvirt/images/{{item}}.qcow2

#- name: create base disk
#  command: qemu-img create -f qcow2 -b "{{ baseImageDirectory }}/{{ baseImageFilename }}" /var/lib/libvirt/images/{{item}}.qcow2

- name: create vms
  command: virt-install -n {{item}} --memory "{{ ramMb }}" --disk "/var/lib/libvirt/images/{{ item }}.qcow2" --disk "/var/lib/libvirt/images/{{ item }}.iso,device=cdrom" --import --noautoconsole --os-variant rhel7 --vcpus "{{ vcpuCount }}" --cpu host
  when: vmCustomize == "cloud-init"

- when: vmCustomize == "virt-customize"
  block: 
  - name: customize vm
    command: virt-customize -a "/var/lib/libvirt/images/{{ item }}.qcow2" --root-password password:password --uninstall cloud-init --hostname "{{ item }}" --ssh-inject root:file:/root/.ssh/id_rsa.pub --selinux-relabel

  - name: sm register
    command: virt-customize -a "/var/lib/libvirt/images/{{ item }}.qcow2" --sm-credentials "{{ rh_username }}:password:{{ rh_password }}" --sm-register --sm-attach auto
    when: rh_username is defined and rh_password is defined

  - name: create vms
    command: virt-install -n {{item}} --memory "{{ ramMb }}" --disk "/var/lib/libvirt/images/{{ item }}.qcow2" --import --noautoconsole --os-variant rhel7 --vcpus "{{ vcpuCount }}" --cpu host

- name: create vms
  command: virt-install -n {{item}} --memory "{{ ramMb }}" --disk "/var/lib/libvirt/images/{{ item }}.qcow2" --import --noautoconsole --os-variant rhel7 --vcpus "{{ vcpuCount }}" --cpu host
  when: vmCustomize != "virt-customize" or vmCustomize != "cloud-init"

