---
- hosts: all
  roles:
    - common

- hosts: webserver
  roles:
    - webserver

- hosts: jenkins
  roles:
    - jenkins

- hosts: hypervisor
  roles: 
    - hypervisor

- hosts: kiosk
  roles: 
    - kiosk
