apiVersion: v1
kind: PersistentVolume
metadata:
  name: "NAMESPACE-VOLUME_NAME"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: "VOLUME_NAME"
    namespace: "NAMESPACE"
  nfs:
    path: PATH
    server: openshift.teratan.net
