---
- apt: name={{item}} state=absent
  with_items:
    - xscreensaver
  when: ansible_distribution == "debian"

- apt: name={{item}} state=present
  with_items:
    - unclutter

- copy:
    src: lxde-autostart
    dest: /home/pi/.config/lxsession/LXDE-pi/autostart

#- copy:
#    src: fluxbox-startup
#    dest: /home/pi/.fluxbox/startup

#- copy:
#    src: xinitrc
#    dest: /home/pi/.xinitrc

