#!/usr/bin/env python3

import os
import glob

os.chdir("/jwrFs/Software/PC/OS")

files = glob.glob("*")
files = filter(lambda f: os.path.isfile(f), files)
files = filter(lambda f: ".iso" not in f, files)
files = sorted(files)

for f in files:
    print(f)
