#!/usr/bin/env python3

import os
import glob
import dialog

os.chdir("/jwrFs/Software/PC/OS")

files = glob.glob("*")
files = filter(lambda f: os.path.isfile(f), files)
files = filter(lambda f: ".iso" not in f, files)
files = sorted(files)
files = map(lambda f: (f,""), files)

d = dialog.Dialog()
status, img = d.menu(text = "Select an image;", choices=files)

if status == d.OK:
    os.system("~/scripts/ansible-playbooks/vmcreator-libvirt/create.yml -e baseImageFilename=" + img + " -l localhost")

print()
