---
- yum: name={{item}} state=present
  with_items: 
    - libvirt
    - virt-install 
    - bridge-utils
    - qemu-kvm 
    - qemu-img 
    - qemu-system-x86
    - qemu-kvm-tools

- service: name=libvirtd state=started enabled=yes 
