#!/usr/bin/env bash

ansible-libvirt-create.yml -ebaseImageFilename=Fedora-Cloud-Base-36-1.5.x86_64.qcow2 -ecount=1 -eramMb=4192 -evmCustomize=cloud-init -ediskSize=8 -eextraVirtInstall="" -eextraVirtCustomize=""
