#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_prompt:
  - name: "SERVER_BMC"
    prompt: "Server BMC Address?"
    default: 192.168.66.7
    private: no
  - name: "SERVER_IP"
    prompt: "Server IP Address?"
    default: 192.168.66.10
    private: no
  - name: "PASSWORD"
    prompt: "Password for superone IPMI?"
    private: yes
  tasks:
  - name: switch
    wait_for: 
      host: procurve
      port: 80
      timeout: 10
  - name: server bmc network
    wait_for: 
      host: "{{ SERVER_BMC }}"
      port: 80
  - name: server bmc power
    ipmi_power: 
      name: "{{ SERVER_BMC }}"
      user: ADMIN
      password: "{{ PASSWORD }}"
      state: on
  - name: server ping after power on
    wait_for: 
      host: "{{ SERVER_IP }}"
      port: 22
